//@ui5-bundle com/exercise/onlinestoresapui5/Component-preload.js
sap.ui.require.preload({
	"com/exercise/onlinestoresapui5/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","./model/models"],function(t,e,i){"use strict";return t.extend("com.exercise.onlinestoresapui5.Component",{metadata:{manifest:"json"},init:function(){t.prototype.init.call(this);this.setModel(i.createDeviceModel(),"device");this.getRouter().initialize()},getContentDensityClass:function(){if(this.contentDensityClass===undefined){if(document.body.classList.contains("sapUiSizeCozy")||document.body.classList.contains("sapUiSizeCompact")){this.contentDensityClass=""}else if(!e.support.touch){this.contentDensityClass="sapUiSizeCompact"}else{this.contentDensityClass="sapUiSizeCozy"}}return this.contentDensityClass}})});
},
	"com/exercise/onlinestoresapui5/controller/App.controller.js":function(){sap.ui.define(["./BaseController"],function(e){"use strict";return e.extend("com.exercise.onlinestoresapui5.controller.App",{onInit:function(){this.getView().addStyleClass(this.getOwnerComponent().getContentDensityClass())}})});
},
	"com/exercise/onlinestoresapui5/controller/BaseController.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/UIComponent","sap/ui/core/routing/History"],function(e,t,n){"use strict";return e.extend("com.exercise.onlinestoresapui5.controller.BaseController",{getOwnerComponent:function(){return e.prototype.getOwnerComponent.call(this)},getRouter:function(){return t.getRouterFor(this)},getResourceBundle:function(){const e=this.getOwnerComponent().getModel("i18n");return e.getResourceBundle()},getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){this.getView().setModel(e,t);return this},navTo:function(e,t,n){this.getRouter().navTo(e,t,undefined,n)},onNavBack:function(){const e=n.getInstance().getPreviousHash();if(e!==undefined){window.history.go(-1)}else{this.getRouter().navTo("main",{},undefined,true)}}})});
},
	"com/exercise/onlinestoresapui5/controller/Main.controller.js":function(){sap.ui.define(["./BaseController","sap/m/MessageBox"],function(e,o){"use strict";return e.extend("com.exercise.onlinestoresapui5.controller.Main",{sayHello:function(){o.show("Hello World!")}})});
},
	"com/exercise/onlinestoresapui5/i18n/i18n.properties":'appTitle=Online-store (SAPUI5)\nappDescription=UI5 Application: Online-store\nbtnText=Say Hello',
	"com/exercise/onlinestoresapui5/i18n/i18n_en.properties":'appTitle=Online-store (SAPUI5)\nappDescription=UI5 Application: Online-store\nbtnText=Say Hello',
	"com/exercise/onlinestoresapui5/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"com.exercise.onlinestoresapui5","type":"application","i18n":"i18n/i18n.properties","title":"{{appTitle}}","description":"{{appDescription}}","applicationVersion":{"version":"1.0.0"}},"sap.ui":{"technology":"UI5","icons":{},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"com.exercise.onlinestoresapui5.view.App","type":"XML","async":true,"id":"app"},"dependencies":{"minUI5Version":"1.112.1","libs":{"sap.ui.core":{},"sap.ui.layout":{},"sap.ui.unified":{},"sap.m":{}}},"handleValidation":true,"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.exercise.onlinestoresapui5.i18n.i18n"}}},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"com.exercise.onlinestoresapui5.view","controlId":"app","controlAggregation":"pages","async":true},"routes":[{"pattern":"","name":"main","target":"main"}],"targets":{"main":{"viewId":"main","viewName":"Main"}}}}}',
	"com/exercise/onlinestoresapui5/model/formatter.js":function(){sap.ui.define(function(){"use strict";return{formatValue:r=>{if(!r){return""}try{return parseFloat(r).toFixed(2)}catch(t){return r}}}});
},
	"com/exercise/onlinestoresapui5/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/model/BindingMode","sap/ui/Device"],function(e,i,n){"use strict";return{createDeviceModel:()=>{const d=new e(n);d.setDefaultBindingMode(i.OneWay);return d}}});
},
	"com/exercise/onlinestoresapui5/view/App.view.xml":'<mvc:View\n\tcontrollerName="com.exercise.onlinestoresapui5.controller.App"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"><App id="app" /></mvc:View>',
	"com/exercise/onlinestoresapui5/view/Main.view.xml":'<mvc:View\n\tcontrollerName="com.exercise.onlinestoresapui5.controller.Main"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"><MessagePage\n\t\ttitle="{i18n>appTitle}"\n\t\ttext="{i18n>appTitle}"\n\t\ticon="sap-icon://accept"\n\t\tid="page"\n\t\tdescription="{i18n>appDescription}"><buttons><Button\n\t\t\t\ttext="{i18n>btnText}"\n\t\t\t\tpress="sayHello" /></buttons></MessagePage></mvc:View>'
});
